name: print-name

on:
        push:
                branches:
                  - main

jobs:
        printjob:
         runs-on: ubuntu-latest
         steps:
                 - name: Checkout code
                   use: actions/checkout@v4

                 - name: Printing Message......
                   run: |
                         echo "This is Print-Name"
