name: print-name

on:
  push:
    branches:
      - main

jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4   # Ensure this says "uses", not "use"

      - name: Print Message
        run: echo " The is print-name"

